kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: svenc56/teamspeak-channelcreator
      dockerfile: Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
