kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: svenc56/teamspeak-channelcreator
      dockerfile: Dockerfile
      tag: ["latest", "alpine", "v1.${DRONE_BUILD_NUMBER}"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
