kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: svenc56/discourse-teamspeak-bridge
      dockerfile: Dockerfile
      tag: ["latest", "alpine", "${DRONE_BUILD_NUMBER}"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
